# Generated by Django 4.1.7 on 2023-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_phone',
            field=models.CharField(max_length=500),
        ),
    ]
