# Generated by Django 4.1.7 on 2023-06-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_userdata_user_email_alter_userdata_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coffee_name', models.CharField(max_length=100, verbose_name='Name Of Coffe')),
                ('Coffee_Type', models.CharField(max_length=100, verbose_name='Type Of Coffe')),
                ('Coffee_description', models.CharField(max_length=500, verbose_name='Small Description')),
                ('Coffee_price', models.IntegerField(default=0, verbose_name='Price')),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_email',
            field=models.CharField(max_length=500, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_phone',
            field=models.CharField(max_length=500, verbose_name='Phone'),
        ),
    ]
