# Generated by Django 4.1.7 on 2023-06-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_coffee_alter_userdata_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='Coffee_image',
            field=models.ImageField(default='', upload_to='', verbose_name='Image For Coffe'),
            preserve_default=False,
        ),
    ]
