# Generated by Django 4.1.7 on 2023-06-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_coffee_coffee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_publish_date', models.DateField()),
                ('blog_description', models.TextField()),
                ('blog_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
