# Generated by Django 4.1.7 on 2023-06-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
